include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-restApiPostProject',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-restApiPostProject',
    'Gerrit-SshModule: com.googlesource.gerrit.plugins.examples.restapipostproject.SshModule',
    'Implementation-Title: Example Simple Ssh Command',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

# TODO(davido): is this needed?
# requires for bucklets/tools/eclipse/project.py to work
# not sure, if this does something useful in standalone context
java_library(
  name = 'classpath',
  deps = [':example-restApiPostProject__plugin'],
)
