include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-validationListenerAssignee',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-validationListenerAssignee',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.validationlistenerassignee.Module',
    'Implementation-Title: Example Validation Listener Assignee',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-validationListenerAssignee__plugin'],
)
