genrule(
    name = "all",
    srcs = [
        "//example-adminSshCommand",
        "//example-changeHasOperator",
        "//example-changeOperator",
        "//example-changeQueryAttributes",
        "//example-commitValidator",
        "//example-consoleMetricReporter",
        "//example-deployedOnIncludedInExtension",
        "//example-restApiCommandOption",
        "//example-restApiGetRevision",
        "//example-restApiPostProject",
        "//example-restApiPostRevision",
        "//example-servlet",
        "//example-simpleSshCommand",
        "//example-sshAndRestCommandOptionBeanParseListener",
        "//example-sshCommandAlias",
        "//example-sshCommandOption",
        "//example-topMenu",
        "//example-usageDataLogger",
        "//example-validationListenerAssignee",
        "//example-validationListenerCommit",
        "//example-validationListenerHashtag",
        "//example-validationListenerMerge",
        "//example-validationListenerNewProjectCreated",
        "//example-validationListenerRefOperation",
        "//example-validationListenerUpload",
        "//example-webLinkBranch",
        "//example-webLinkFileHistory",
        "//example-webLinkPatchSet",
        "//example-webLinkProject",
        "//example-wuiChangeScreenBelowChangeInfoBlock",
        "//example-wuiChangeScreenHeader",
        "//example-wuiChangeScreenHeaderRightOfButtons",
        "//example-wuiChangeScreenHeaderRightOfPopDowns",
        "//example-wuiPreferenceScreenBottom",
        "//example-wuiProfileExtensionBottom",
        "//example-wuiSettingsScreen",
    ],
    outs = ["all.zip"],
    cmd = " && ".join([
        "p=$$PWD",
        "t=$$(mktemp -d || mktemp -d -t bazel-tmp)",
        "cp $(SRCS) $$t",
        "cd $$t",
        "zip -qr $$p/$@ .",
    ]),
)
