include_defs('//bucklets/gerrit_plugin.bucklet')

MODULE = "com.googlesource.gerrit.plugins.examples.wuisettingsscreen.HelloForm"

gerrit_plugin(
  name = 'example-wuiSettingsScreen',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  gwt_module = MODULE,
  manifest_entries = [
    'Gerrit-PluginName: example-wuiSettingsScreen',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.wuisettingsscreen.Module',
    'Implementation-Title: Example Settings Screen Extension',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-wuiSettingsScreen__plugin'],
)
