include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-denyUpload',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-denyUpload',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.denyupload.Module',
    'Implementation-Title: Deny Upload Example',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-denyUpload__plugin'],
)
