include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-restApiCommandOption',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-restApiCommandOption',
    'Gerrit-HttpModule: com.googlesource.gerrit.plugins.examples.restapicommandoption.HttpModule',
    'Implementation-Title: Example Simple REST Command Option',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-restApiCommandOption__plugin'],
)
