include_defs('//bucklets/gerrit_plugin.bucklet')

MODULE = "com.googlesource.gerrit.plugins.examples.wuichangescreennew.HelloForm"

gerrit_plugin(
  name = 'example-wuiChangeScreenNew',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  gwt_module = MODULE,
  manifest_entries = [
    'Gerrit-PluginName: example-wuiChangeScreenNew',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.wuichangescreennew.Module',
    'Implementation-Title: Example Change Screen',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-wuiChangeScreenNew__plugin'],
)
