include_defs('//bucklets/gerrit_plugin.bucklet')

MODULE = "com.googlesource.gerrit.plugins.examples.wuichangescreenbelowchangeinfoblock.HelloForm"

gerrit_plugin(
  name = 'example-wuiChangeScreenBelowChangeInfoBlock',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  gwt_module = MODULE,
  manifest_entries = [
    'Gerrit-PluginName: example-wuiChangeScreenBelowChangeInfoBlock',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.wuichangescreenbelowchangeinfoblock.Module',
    'Implementation-Title: Example Change Screen Extension Below Change Info Block',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-wuiChangeScreenBelowChangeInfoBlock__plugin'],
)
