include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-sshCommandOption',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-sshCommandOption',
    'Gerrit-SshModule: com.googlesource.gerrit.plugins.examples.sshcommandoption.SshModule',
    'Implementation-Title: Example Simple SSH Command Option',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-sshCommandOption__plugin'],
)
