include_defs('//bucklets/gerrit_plugin.bucklet')

MODULE = "com.googlesource.gerrit.plugins.examples.wuichangescreenheaderrightofpopdowns.HelloForm"

gerrit_plugin(
  name = 'example-wuiChangeScreenHeaderRightOfPopDowns',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  gwt_module = MODULE,
  manifest_entries = [
    'Gerrit-PluginName: example-wuiChangeScreenHeaderRightOfPopDowns',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.wuichangescreenheaderrightofpopdowns.Module',
    'Implementation-Title: Example Change Screen Header Extension Right Of Pop Downs',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-wuiChangeScreenHeaderRightOfPopDowns__plugin'],
)
