include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-deployedOnIncludedInExtension',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-deployedOnIncludedInExtension',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.deployedonincludedinextension.Module',
    'Implementation-Title: Example Deployed On Included-In Extension',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-deployedOnIncludedInExtension__plugin'],
)
