include_defs('//bucklets/gerrit_plugin.bucklet')

MODULE = "com.googlesource.gerrit.plugins.examples.wuipluginscreen.HelloForm"

gerrit_plugin(
  name = 'example-wuiPluginScreen',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  gwt_module = MODULE,
  manifest_entries = [
    'Gerrit-PluginName: example-wuiPluginScreen',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.wuipluginscreen.Module',
    'Implementation-Title: Example Plugin Screen Extension',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-wuiPluginScreen__plugin'],
)
