include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-sshCommandAlias',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-sshCommandAlias',
    'Gerrit-SshModule: com.googlesource.gerrit.plugins.examples.sshcommandalias.SshModule',
    'Implementation-Title: Example Ssh Command Alias',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-sshCommandAlias__plugin'],
)
