include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-restApiGetRevision',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-restApiGetRevision',
    'Gerrit-SshModule: com.googlesource.gerrit.plugins.examples.restapigetrevision.SshModule',
    'Implementation-Title: Example Simple Ssh Command',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-restApiGetRevision__plugin'],
)
