include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-sshCommandDelegateDynamicBean',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-sshCommandDelegateDynamicBean',
    'Gerrit-SshModule: com.googlesource.gerrit.plugins.examples.sshcommanddelegatedynamicbean.SshModule',
    'Implementation-Title: Example Admin Ssh Command',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-sshCommandDelegateDynamicBean__plugin'],
)
