include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-servlet',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-servlet',
    'Gerrit-HttpModule: com.googlesource.gerrit.plugins.examples.servlet.HttpModule',
    'Implementation-Title: Example Servlet',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-servlet__plugin'],
)
