include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-sshChangeQueryAttributes',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-sshChangeQueryAttributes',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.sshchangequeryattributes.Module',
    'Implementation-Title: Example Simple SSH Change Query Attribute',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-sshChangeQueryAttributes__plugin'],
)
