include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-topMenu',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: cookbook',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.topmenu.Module',
    'Implementation-Title: Cookbook plugin',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_test(
  name = 'examples_tests',
  srcs = glob(['src/test/java/**/*IT.java']),
  labels = ['example-topMenu'],
  deps = GERRIT_PLUGIN_API + GERRIT_TESTS + [
    ':example-topMenu__plugin',
  ],
)

# TODO(davido): is this needed?
# requires for bucklets/tools/eclipse/project.py to work
# not sure, if this does something useful in standalone context
java_library(
  name = 'classpath',
  deps = [':example-topMenu__plugin'],
)
