include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-commitValidator',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-commitValidator',
    'Gerrit-Module: com.googlesource.gerrit.plugins.examples.commitvalidator.Module',
    'Implementation-Title: Example Commit Validator',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-commitvalidator__plugin'],
)
