include_defs('//bucklets/gerrit_plugin.bucklet')

gerrit_plugin(
  name = 'example-sshCommandOptionBeanParseListener',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/**/*']),
  manifest_entries = [
    'Gerrit-PluginName: example-sshCommandOptionBeanParseListener',
    'Gerrit-SshModule: com.googlesource.gerrit.plugins.examples.sshcommandoption.SshModule',
    'Implementation-Title: Example Simple SSH Command Option Bean Parse Listner',
    'Implementation-URL: https://gerrit-review.googlesource.com/#/admin/projects/plugins/examples',
  ],
)

java_library(
  name = 'classpath',
  deps = [':example-sshCommandOptionBeanParseListener__plugin'],
)
